// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dmUBM6I8oJaCpr2195d3gx4F7P4EdRY',
    appId: '1:1070126257893:web:f355543700a186e97f660c',
    messagingSenderId: '1070126257893',
    projectId: 'wellnessvault0',
    authDomain: 'wellnessvault0.firebaseapp.com',
    storageBucket: 'wellnessvault0.appspot.com',
    measurementId: 'G-GS3FQ8QKLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFmWycaRalOuYr5Livx2nqJHyXHHhbN8',
    appId: '1:1070126257893:android:ccc3b3f77d40b61f7f660c',
    messagingSenderId: '1070126257893',
    projectId: 'wellnessvault0',
    storageBucket: 'wellnessvault0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu6zWhNzNz44y1r8EsGyLkalgynweZC4A',
    appId: '1:1070126257893:ios:0d46ce4fa0aa69cd7f660c',
    messagingSenderId: '1070126257893',
    projectId: 'wellnessvault0',
    storageBucket: 'wellnessvault0.appspot.com',
    iosBundleId: 'com.example.wellnessvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu6zWhNzNz44y1r8EsGyLkalgynweZC4A',
    appId: '1:1070126257893:ios:0d46ce4fa0aa69cd7f660c',
    messagingSenderId: '1070126257893',
    projectId: 'wellnessvault0',
    storageBucket: 'wellnessvault0.appspot.com',
    iosBundleId: 'com.example.wellnessvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dmUBM6I8oJaCpr2195d3gx4F7P4EdRY',
    appId: '1:1070126257893:web:d57de8cc121324367f660c',
    messagingSenderId: '1070126257893',
    projectId: 'wellnessvault0',
    authDomain: 'wellnessvault0.firebaseapp.com',
    storageBucket: 'wellnessvault0.appspot.com',
    measurementId: 'G-6Y88L2CHLW',
  );
}
